# Introduction

This chapter provides an overview of contemporary machine learning. We'll cover
important terminology and popular methods so that you can determine whether
machine learning is relevant to your research and what to learn more about if
it is. This is a concept-focused, non-technical chapter.

::: {.callout-note title="Learning Goals"}
After this workshop, learners should be able to:

* Define the following terms: observation, feature, machine learning,
  supervised learning, unsupervised learning, regression, classification,
  clustering, training set, validation set, test set, cross-validation,
  overfitting, underfitting, model bias, model variance, bias-variance
  tradeoff, ensemble model.
* Explain the difference between supervised and unsupervised learning.
* Explain the difference between regression and classification.
* List and briefly describe popular machine learning methods.
* Give an example of an ensemble model.
* Explain what cross-validation is used for and give an overview of the
  procedure.
* Assess whether and which machine learning methods might be helpful for a
  given research problem.
:::


## What Is Machine Learning?
